spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    database: mysql
    hibernate:
      ddl-auto: update

auth:
  jwt:
    secret: ${JWT_SECRET}
    exp:
      access: ${JWT_ACCESS_EXP}
      refresh: ${JWT_REFRESH_EXP}

oauth:
  google:
    client_id: ${GOOGLE_CLIENT_ID}
    client_secret: ${GOOGLE_CLIENT_SECRET}
    redirect_uri: ${GOOGLE_REDIRECT_URI}