auth:
  jwt:
    secret: ${JWT_SECRET}
    exp:
      access: ${JWT_ACCESS_EXP}
      refresh: ${JWT_REFRESH_EXP}

oauth:
  google:
    client_id: ${GOOGLE_CLIENT_ID}
    client_secret: ${GOOGLE_CLIENT_SECRET}
    redirect_uri: ${GOOGLE_REDIRECT_URI}